apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: genai-perf-analyze-template
  annotations:
    workflows.argoproj.io/description: |
      GenAI Performance test
spec:
  arguments:
    parameters:
    - name: gpu-type
      description: "GPU type (a100, rtx4090, a5000, a6000)"
    - name: service-url
      description: "URL of the vLLM service"
    - name: model-name
      description: "model name from HF"
    - name: endpoint-type
      default: "completions"
    - name: output-tokens-mean
      default: "20"
    - name: output-tokens-stddev
      default: "10"
    - name: sweep-type
      default: "concurrency"
    - name: sweep-list
      default: "1,2,3"
    - name: synthetic-input-tokens-mean
      default: "20"
    - name: synthetic-input-tokens-stddev
      default: "10"
    - name: request-count
      default: "10"
  entrypoint: genai-perf 
  serviceAccountName: argo-workflow
  templates:
  - name: genai-perf
    inputs:
      parameters:
        - name: gpu-type
    container:
      image: nvcr.io/nvidia/tritonserver:25.08-py3-sdk
      command: ["genai-perf"]
      args: [
        "analyze",
        "-m", "{{workflow.parameters.model-name}}",
        "--sweep-type", "{{workflow.parameters.sweep-type}}",
        "--sweep-list", "{{workflow.parameters.sweep-list}}",
        "--url", "{{workflow.parameters.service-url}}",
        "--endpoint-type", "{{workflow.parameters.endpoint-type}}",
        "--output-tokens-mean", "{{workflow.parameters.output-tokens-mean}}",
        "--output-tokens-stddev", "{{workflow.parameters.output-tokens-stddev}}",
        "--synthetic-input-tokens-mean", "{{workflow.parameters.synthetic-input-tokens-mean}}",
        "--synthetic-input-tokens-stddev", "{{workflow.parameters.synthetic-input-tokens-stddev}}",
        "--request-count", "{{workflow.parameters.request-count}}",
        "--warmup-request-count", "5",
        "--verbose"
      ]
      env:
      - name: HF_TOKEN
        valueFrom:
          secretKeyRef:
            name: hf-token-secret
            key: hf-token
      volumeMounts:
      - name: nfs-volume
        mountPath: /workspace/
        subPath: "{{ inputs.parameters.gpu-type }}"
      - name: prompt-volume
        mountPath: /prompts
  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs-pvc
  - name: prompt-volume
    configMap:
      name: genai-perf-input-configmap